-- Insert Users
INSERT INTO users (user_data) VALUES 
(jsonb_build_object('email', 'test@example.com', 'username', 'testuser', 'password', crypt('password123', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'lilianliao0201@gmail.com', 'username', 'lilian', 'password', crypt('ilovehoward', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'james@gmail.com', 'username', 'james', 'password', crypt('james', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'george.harrison@example.com', 'username', 'george', 'password', crypt('professor123', gen_salt('bf')), 'role', 'admin', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'student1@example.com', 'username', 'student1', 'password', crypt('studentpassword1', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'student2@example.com', 'username', 'student2', 'password', crypt('studentpassword2', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'student3@example.com', 'username', 'student3', 'password', crypt('studentpassword3', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'srheam0@myspace.com', 'username', 'Shandra Rheam', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'zjefferys1@vimeo.com', 'username', 'Zerk Jefferys', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'bgrain2@usgs.gov', 'username', 'Burtie Grain', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'mblasius3@youtube.com', 'username', 'Mireielle Blasius', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'sashfold4@soup.io', 'username', 'Sheffy Ashfold', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'vtremonte5@eventbrite.com', 'username', 'Verney Tremonte', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'slearmount6@mayoclinic.com', 'username', 'Sean Learmount', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'fbenjafield7@bizjournals.com', 'username', 'Fayette Benjafield', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'rsnozzwell8@weebly.com', 'username', 'Richard Snozzwell', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'raffleck9@constantcontact.com', 'username', 'Rockey Affleck', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'fmudda@aol.com', 'username', 'Flor Mudd', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'jberggrenb@vimeo.com', 'username', 'Janey Berggren', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'vmonneryc@liveinternet.ru', 'username', 'Vincents Monnery', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'sbirkheadd@yellowbook.com', 'username', 'Stavro Birkhead', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'kconellye@tinyurl.com', 'username', 'Kaitlin Conelly', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'abubbinsf@redcross.org', 'username', 'Angie Bubbins', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'wbrisardg@lycos.com', 'username', 'Wayland Brisard', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'mstainlandh@addthis.com', 'username', 'Monti Stainland', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'kjossei@skyrock.com', 'username', 'Kipper Josse', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'rgreedj@csmonitor.com', 'username', 'Reinold Greed', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'sdorricottk@creativecommons.org', 'username', 'Sukey Dorricott', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'kconstancel@feedburner.com', 'username', 'Kalindi Constance', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'mcullumm@zimbio.com', 'username', 'Merrielle Cullum', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'nhounsomen@addtoany.com', 'username', 'Nat Hounsome', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null))),
(jsonb_build_object('email', 'ppaleyo@joomla.org', 'username', 'Philbert Paley', 'password', crypt('password', gen_salt('bf')), 'role', 'user', 'last_state', jsonb_build_object('lastWorkspace', null, 'lastChannel', null, 'lastMessage', null)));

-- Insert Workspaces
INSERT INTO workspaces (workspace_data) VALUES
(jsonb_build_object('name', 'CSE 186', 'created_by', 'george.harrison@example.com', 'description', 'Computer Science Course')),
(jsonb_build_object('name', 'Project X', 'created_by', 'george.harrison@example.com', 'description', 'Special Project'));

-- Insert Channels
INSERT INTO channels (channel_data) VALUES
(jsonb_build_object('name', 'Assignment 1', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'created_by', 'george.harrison@example.com', 'description', 'First Assignment')),
(jsonb_build_object('name', 'Assignment 2', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'created_by', 'george.harrison@example.com', 'description', 'Second Assignment')),
(jsonb_build_object('name', 'Assignment 3', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'created_by', 'george.harrison@example.com', 'description', 'Third Assignment')),
(jsonb_build_object('name', 'General', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'created_by', 'george.harrison@example.com', 'description', 'General Discussion'));

-- Insert Messages
INSERT INTO messages (message_data) VALUES
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 1'), 'user_email', 'test@example.com', 'content', 'Message for Assignment 1', 'created_at', '2024-07-23T12:00:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'), 'user_email', 'student1@example.com', 'content', 'Hey @lilian, could you help me with the second question?', 'created_at', '2024-07-23T12:05:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'), 'user_email', 'student2@example.com', 'content', 'I agree with @lilian solution on the first question.', 'created_at', '2024-07-23T12:10:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'), 'user_email', 'student3@example.com', 'content', '@lilian, can you check if my answer is correct?', 'created_at', '2024-07-23T12:15:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'), 'user_email', 'lilianliao0201@gmail.com', 'content', 'Message for Assignment 2', 'created_at', '2024-07-23T12:05:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 3'), 'user_email', 'james@gmail.com', 'content', 'Message for Assignment 3', 'created_at', '2024-07-23T12:10:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'george.harrison@example.com', 'content', 'General message in General channel', 'created_at', '2024-07-23T12:15:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'student1@example.com', 'content', 'Hello everyone!', 'created_at', '2024-07-23T12:20:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'student2@example.com', 'content', 'Hi! Excited for this course.', 'created_at', '2024-07-23T12:25:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'student3@example.com', 'content', 'Looking forward to learning!', 'created_at', '2024-07-23T12:30:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'srheam0@myspace.com', 'content', 'Cras non velit nec nisi vulputate nonummy.', 'created_at', '2024-07-23T12:35:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'zjefferys1@vimeo.com', 'content', 'Proin interdum mauris non ligula pellentesque ultrices.', 'created_at', '2024-07-23T12:40:00Z')),
(jsonb_build_object('channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'), 'user_email', 'bgrain2@usgs.gov', 'content', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'created_at', '2024-07-23T12:45:00Z'));

-- Insert Direct Messages
INSERT INTO direct_messages (direct_message_data) VALUES
(jsonb_build_object('sender_email', 'test@example.com', 'receiver_email', 'lilianliao0201@gmail.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'content', 'Hi lilian! So nice to meet you!', 'created_at', '2024-07-23T13:00:00Z')),
(jsonb_build_object('sender_email', 'lilianliao0201@gmail.com', 'receiver_email', 'james@gmail.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'content', 'Howdy, the porfessor had such a great lecture!', 'created_at', '2024-07-23T13:05:00Z')),
(jsonb_build_object('sender_email', 'george.harrison@example.com', 'receiver_email', 'student1@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'content', 'Welcome to the course!', 'created_at', '2024-07-23T13:10:00Z')),
(jsonb_build_object('sender_email', 'george.harrison@example.com', 'receiver_email', 'student2@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'content', 'Let me know if you need any help.', 'created_at', '2024-07-23T13:15:00Z')),
(jsonb_build_object('sender_email', 'george.harrison@example.com', 'receiver_email', 'student3@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'), 'content', 'Good to have you here.', 'created_at', '2024-07-23T13:20:00Z'));

-- Insert User-Workspace Relationships
INSERT INTO user_workspaces (relationship_data) VALUES
(jsonb_build_object('user_email', 'test@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'lilianliao0201@gmail.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'james@gmail.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'student1@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'student2@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'student3@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'srheam0@myspace.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'zjefferys1@vimeo.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'bgrain2@usgs.gov', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'mblasius3@youtube.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'sashfold4@soup.io', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'vtremonte5@eventbrite.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'slearmount6@mayoclinic.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'fbenjafield7@bizjournals.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'rsnozzwell8@weebly.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'raffleck9@constantcontact.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'fmudda@aol.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'jberggrenb@vimeo.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'vmonneryc@liveinternet.ru', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'sbirkheadd@yellowbook.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'kconellye@tinyurl.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'abubbinsf@redcross.org', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'wbrisardg@lycos.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'mstainlandh@addthis.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'kjossei@skyrock.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'rgreedj@csmonitor.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'sdorricottk@creativecommons.org', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'kconstancel@feedburner.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'mcullumm@zimbio.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'nhounsomen@addtoany.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'ppaleyo@joomla.org', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'CSE 186'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'workspace_id', (SELECT id FROM workspaces WHERE workspace_data->>'name' = 'Project X')));

-- Insert User-Channel Relationships
INSERT INTO user_channels (relationship_data) VALUES
(jsonb_build_object('user_email', 'test@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 1'))),
(jsonb_build_object('user_email', 'test@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'))),
(jsonb_build_object('user_email', 'test@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 3'))),
(jsonb_build_object('user_email', 'test@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'lilianliao0201@gmail.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 1'))),
(jsonb_build_object('user_email', 'lilianliao0201@gmail.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'))),
(jsonb_build_object('user_email', 'lilianliao0201@gmail.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 3'))),
(jsonb_build_object('user_email', 'lilianliao0201@gmail.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'james@gmail.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 3'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 1'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 2'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'Assignment 3'))),
(jsonb_build_object('user_email', 'george.harrison@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'student1@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'student2@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'student3@example.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'srheam0@myspace.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'zjefferys1@vimeo.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'bgrain2@usgs.gov', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'mblasius3@youtube.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'sashfold4@soup.io', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'vtremonte5@eventbrite.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'slearmount6@mayoclinic.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'fbenjafield7@bizjournals.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'rsnozzwell8@weebly.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'raffleck9@constantcontact.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'fmudda@aol.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'jberggrenb@vimeo.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'vmonneryc@liveinternet.ru', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'sbirkheadd@yellowbook.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'kconellye@tinyurl.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'abubbinsf@redcross.org', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'wbrisardg@lycos.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'mstainlandh@addthis.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'kjossei@skyrock.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'rgreedj@csmonitor.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'sdorricottk@creativecommons.org', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'kconstancel@feedburner.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'mcullumm@zimbio.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'nhounsomen@addtoany.com', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General'))),
(jsonb_build_object('user_email', 'ppaleyo@joomla.org', 'channel_id', (SELECT id FROM channels WHERE channel_data->>'name' = 'General')));
